### ISSUE TITLE
Is this repository open to pull requests?

### ISSUE THREAD

**Issue by RGBboy** [suitcss/preprocessor#10]
@necolas just wondering what your position is on pull requests? I can see a couple waiting with no comment.

**Comment by necolas** [comment]
I would say "no", and suggest using postcss plugins or projects like cssnext (suitcss uses a subset of its features). I will deprecate this once I get some time to upstream suit-related changes we've made at Twitter.

**Comment by RGBboy** [comment]
OK thanks for the info. I shall look into using them instead. Does this mean suitcss is also going to be deprecated to?

**Comment by simonsmith** [comment]
SUIT is not going away, but the way components are built we likely get an update. See #11
