### ISSUE TITLE
Consider adding stylelint as a core feature

### ISSUE THREAD

**Issue by simonsmith** [suitcss/preprocessor#17]
This [stylelint-config-suitcss](https://github.com/stylelint/stylelint-config-suitcss) is useful, and the core packages should ideally be passing. Might make sense to incorporate it into the preprocessor, and perhaps move it behind a flag, as `bem-linter` is opt-in already (via comments). Users are free to toggle options via `.stylelintrc` once it's running.

Files need to be stylelinted on import, rather than as a package and it feels odd to do linting in the `beforeLint` step which would justify this addition.

Maybe [stylelint-selector-bem-pattern](https://github.com/davidtheclark/stylelint-selector-bem-pattern) could do the job in one go.

**Comment by giuseppeg** [comment]
I vote add this! The only cons I can think of about using `stylelint-selector-bem-pattern` is that it is up to the maintainer to upgrade `postcss-bem-linter`

**Comment by simonsmith** [comment]
Yeah. I thought against it too. Putting just style lint behind a flag would be tough as well.
