### ISSUE TITLE
Upgrade to stylelint 4.x

### ISSUE THREAD

**Issue by simonsmith** [suitcss/preprocessor#21]
It's switched to async now so [this line](https://github.com/suitcss/preprocessor/blob/master/lib/index.js#L134) fails to work. Need to find a way to use promises instead

**Comment by simonsmith** [comment]
Opened an issue - https://github.com/postcss/postcss-import/issues/117

**Comment by simonsmith** [comment]
Done in 8.x! - https://github.com/postcss/postcss-import/releases/tag/8.0.0

**Comment by giuseppeg** [comment]
Nice, probably I can fix this on the weekend

**Comment by simonsmith** [comment]
Done in #25

**Comment by giuseppeg** [comment]
Well `Done`  :+1: :)

**Comment by simonsmith** [comment]
:tada:
