### ISSUE TITLE
Can't figure out how to activate source-map option.

### ISSUE THREAD

**Issue by schoenwaldnils** [suitcss/preprocessor#22]
I tried to generate a .map file
https://github.com/postcss/postcss/blob/master/docs/source-maps.md

package.json:
```
...
  "scripts": {
    "watch": "suitcss --watch --verbose --config config/suitcss.js source/assets/styles/main.css source/build/main.css"
  }
```

suitcss.js:
```
'use strict';

module.exports = {
  map: {
    inline: false
  }
};
```

Cant figure out where I am wrong. Any idea?

**Comment by simonsmith** [comment]
We're not passing any options to postcss in the way you're using them. We can though, perhaps a postcss config object would help.

**Comment by schoenwaldnils** [comment]
Hm, I think I don't really get what you mean :/
I know how to use postcss-plugins and configure them. 
But how do I define the postcss config object?

**Comment by simonsmith** [comment]
I meant we'd need to add the ability to pass options to postcss itself, currently you can't. I can add a `map` option at least, so that you can use that.

**Comment by schoenwaldnils** [comment]
Ah ^^
Looking forward to it!
Thank you

**Comment by giuseppeg** [comment]
<blockquote>currently you can't. I can add a map option at least, so that you can use that.</blockquote>

I'd say let's find a way to pass `postcss` options rather than add the single one.

**Comment by schoenwaldnils** [comment]
>I'd say let's find a way to pass postcss options rather than add the single one.

+1
seems more logical to me too
all or nothing :D
