### ISSUE TITLE
Add browserslist config

### ISSUE THREAD

**Issue by simonsmith** [suitcss/preprocessor#34]
As discussed in this thread - https://github.com/suitcss/preprocessor/pull/32#issuecomment-248226557

Based on the SUIT CSS browser support list we should add a [browserslist config](https://github.com/ai/browserslist) that ensures those browsers are supported. This might be a good time to revise the support list too.

**Comment by simonsmith** [comment]
The browser list from the Grid component might be a good starting point as I tested it on mobile devices too:

* Google Chrome (latest)
* Opera (latest)
* Firefox (latest)
* Safari 6.2+
* Internet Explorer 10+
* iOS 7+
* Android 4.4+
* Windows Phone 8.1+

This covers the flexbox minimum and means we don't have to use two separate lists like on the main `suit` repo.

If we were to translate that into a browserlist config it might look like:

```
> 1%, last 2 versions, safari > 6, ie > 9, ios > 6, android > 4.3, samsung > 3, chromeandroid > 50
```

The `> 1%` and `last 2 versions` sets a baseline to catch some browsers like UC and the rest are configured to closely match the list above.

You can see it here - http://browserl.ist/?q=%3E+1%25%2C+last+2+versions%2C+safari+%3E+6%2C+ie+%3E+9%2C+ios+%3E+6%2C+android+%3E+4.3%2C+samsung+%3E+3%2C+chromeandroid+%3E+50

**Comment by giuseppeg** [comment]
I was also looking at [CRA](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js#L189) for a big oss project and [Automattic](https://github.com/Automattic/wp-calypso/blob/master/Makefile#L24) for a real world mid-to-big size app.
But your suggestion looks fine to me and more accurate.

**Comment by giuseppeg** [comment]
In this branch we should probably test autoprefixer differently i.e. make sure that it is invoked instead of comparing input with expected output.. that's already been tested in autoprefixer :)

The reason is that with a browserslist like "> 1%, last 2 versions" prefixes get dropped overtime and test will keep failing.

**Comment by simonsmith** [comment]
I think testing the CSS output is still useful. All the plugins (not just autoprefixer) are tested, but it's useful to have our own integration tests as it were. Will catch issues if we removed one by accident for example.

We could add a different browserslist config for the tests that would fix it some browser versions and the output would not change then.

**Comment by giuseppeg** [comment]
Yep we can do that too imho testing plugins is a bit out of scope since they have tests already.

**Comment by simonsmith** [comment]
Yeah, it's more that our package is using them correctly. Checking that a single declaration is preprocessed is enough. Each plugin obviously has far more rigorous testing but we still want to be confident the preprocessor is using them as expected.

**Comment by giuseppeg** [comment]
Should we go for `> 1%, last 2 versions, safari > 6, ie > 9, ios > 6, android > 4.3, samsung > 3, chromeandroid > 50` ?

**Comment by simonsmith** [comment]
Yeah, that seems good to me
