### ISSUE TITLE
Remove beforeLint

### ISSUE THREAD

**Issue by simonsmith** [suitcss/preprocessor#35]
I feel like this feature is probably unused and adds a lot of complexity to the preprocessor. I think it would also fix #27.

The only use case I had before was to unwrap nested rules for the `bem-linter` but it handles that out of the box now.

Thoughts?

**Comment by giuseppeg** [comment]
I am ok with dropping it. @timkelty ?

**Comment by timkelty** [comment]
OK with me.

**Comment by simonsmith** [comment]
Gonna pick this up
