### ISSUE TITLE
mergeOptions shouldn't override postcss-import's transform

### ISSUE THREAD

**Issue by giuseppeg** [suitcss/preprocessor#36]
In `mergeOptions` we [override](https://github.com/suitcss/preprocessor/blob/master/lib/index.js#L100) `postcss-import`'s `transform` method.

We should instead wrap it and combine it with `lintImportedFiles`.

As I said on gitter `beforeLint` is a special case of `transform` so we might as well fix #35 in this branch.

**Comment by simonsmith** [comment]
Noticed we're also overriding `onImport` too

**Comment by giuseppeg** [comment]
Good catch @simonsmith I can work on this when #35 is merged

**Comment by simonsmith** [comment]
So, I'm kinda half way through because I started `beforeLint` removal and noticed this issue said might as well do both at once.

**Comment by simonsmith** [comment]
Yeah, I can push the beforeLint stuff now. Keep the PRs focussed
