### ISSUE TITLE
Add debug option

### ISSUE THREAD

**Issue by giuseppeg** [suitcss/preprocessor#39]
It would be nice if we could pass an instance of `postcss-debug` via options.

```javascript
import { createDebugger } from 'postcss-debug';
const debug = createDebugger();

suitcss(css, { debug }).then(()=>debug.inspect())
```

By default `debug` would be an identity function that does nothing:

```javascript
var defaults = {
  debug: function (plugins) { return plugins; }
};
```

More on `postcss-debug` https://github.com/andywer/postcss-debug

**Comment by simonsmith** [comment]
This is a nice idea
