### ISSUE TITLE
Consider adding postcss-autoreset

### ISSUE THREAD

**Issue by giuseppeg** [suitcss/preprocessor#43]
It would be nice to get [postcss-autoreset](https://github.com/maximkoretskiy/postcss-autoreset) on Components files by default.
See [this gist](https://gist.github.com/giuseppeg/ad9dd10cfe0e32879ef4713fdb159f80) for a sample config.

Internally the preprocessor should somehow pass this plugin only on components i.e. files that contain a `@define` directive.

**Comment by simonsmith** [comment]
Interesting. So this would negate the need for `suitcss-base` and allow components to not care about styles in the host page?

**Comment by giuseppeg** [comment]
Potentially yes but keep in mind that the reset rules specificity is still `0010`.
I still use normalise + base.

**Comment by giuseppeg** [comment]
blocker https://github.com/maximkoretskiy/postcss-autoreset/issues/16

**Comment by simonsmith** [comment]
Unblocked 🎉

**Comment by simonsmith** [comment]
Done in #53
