### ISSUE TITLE
Consider adding postcss-apply

### ISSUE THREAD

**Issue by giuseppeg** [suitcss/preprocessor#44]
It can be handy and I personally like the syntax.

@tabatkins sorry to bother you, do you think that it is safe to consider this feature future-proof or are there chances that it'll be discarded?

Interesting thread https://github.com/tabatkins/specs/issues/43

**Comment by tabatkins** [comment]
Nothing is safe until it ships in 2 browsers.

**Comment by giuseppeg** [comment]
@tabatkins yeah that was my thought the other day.

@simonsmith maybe we should consider reverting this commit and let the users decide what to add?

[People is scared as phuck](https://github.com/google/material-design-lite/issues/4539) to use not standard and w3c recommended features.

Even though one could argue that all this fear is a bit silly because postcss could be used as refactoring tool with codemod-like plugins, it is probably still a good idea to keep the plugins set to the bare minimum to avoid lots of bug reports and such.

**Comment by simonsmith** [comment]
Couldn't the same logic be applied to the `color-function` and `custom-media`? 

There is always quite a bit of FUD around postcss from Sass developers, so not sure that is a fair test but if you think it's risky adding `apply` then I'm happy to remove it.

**Comment by simonsmith** [comment]
If we were to follow the 'ships in two browsers rule' (which sounds sensible) is there anything else [from this list](http://cssnext.io/features/) that falls into that category? If so we could add those too.

Would be good to follow a rule like that for plugin inclusion rather than ones that we personally use.

**Comment by giuseppeg** [comment]
@simonsmith I guess that we can add all features that are at a `Candidate Recommendation` stage if the plugins are [somehow] stable. So I guess that none of them qualifies.

Should we remove apply and color function?

**Comment by simonsmith** [comment]
My feeling is keep them. I don't share the same fear that the postcss plugins will suddenly become abandoned. Has that happened somewhere else?

I think in the event of that we could convince the author to move them under the postcss org. With cssnext depending on them too there would be interest in keeping them going.
