### ISSUE TITLE
Lint by default

### ISSUE THREAD

**Issue by simonsmith** [suitcss/preprocessor#48]
Thinking it makes more sense to have this on as a default.

**Comment by giuseppeg** [comment]
I was thinking the exact same thing today. `lint` should be on by default.

**Comment by giuseppeg** [comment]
@simonsmith on the other hand today I was thinking that linting is something that I've ran with a pre-commit hook or `npm test`.

However since we are already using `postcss-bem-linter` maybe it is fine to enable it.

**Comment by simonsmith** [comment]
I don't think that having it on or off changes how that work flow would function. If you wanted to lint separately to preprocessing you'd need to set up stylelint outside of the preprocessor.

**Comment by giuseppeg** [comment]
oh nvm I just sa that `postcss-reporter`'s `throwError` is `false` by default

**Comment by simonsmith** [comment]
That brings me neatly to another suggestion :)

 Having an `-e` flag to throw error. In nearly every SUIT repo we have a config file that sets `lint` to `true`, and `throwError` to true. With an extra cli flag we could eliminate that config file entirely.

**Comment by giuseppeg** [comment]
Sounds good to me
