### ISSUE TITLE
Support double-slash comment style

### ISSUE THREAD

**Issue by tauren** [suitcss/preprocessor#5]
I'm building a component-based application and am evaluating suitcss. I'm impressed, as it appears to be designed to suit (pun intended) my use case. I've used less, sass, stylus, etc. in the past, but am willing to switch to the best tool for the task. 

However, the simple lack of `// comment styles` is quite annoying and makes it much harder to quickly comment and uncomment styles as I'm working on them. I understand that one objective of suitcss is to maintain future CSS standards, but it would be great if there was at least an option to use multiple commenting styles.

**Comment by simonsmith** [comment]
Latest release is now based on PostCSS which would allow usage of [postcss-scss](https://github.com/postcss/postcss-scss). That should get you `//` comments.
