### ISSUE TITLE
CLI options should override config file

### ISSUE THREAD

**Issue by simonsmith** [suitcss/preprocessor#54]
Currently I think CLI options are overridden by the config file:

``` js
var opts = assign({}, {
      minify: program.minify,
      root: program.importRoot,
      lint: program.lint
    }, config);
```

AFAIK it's most common to be the other way round as it's often useful to be able to override a single config option on the CLI.

Should be a simple change and maybe a test to verify.

**Comment by giuseppeg** [comment]
Makes perfectly sense. Imo we should merge this before #53

**Comment by simonsmith** [comment]
Think I found a bug with this. Object.assign doesn't ignore undefined values, so:

```js
Object.assign({test: 'hello'}, {test: undefined})
> Object {test: undefined}
```

If I set `encapsulate: true` in the options but leave it undefined on the  CLI (as expected) then it passes `encapsulate: undefined` into the preprocessor

**Comment by giuseppeg** [comment]
Oh right good catch! this must be true for all of the options right?

**Comment by simonsmith** [comment]
Yeah. We still want all the options to merge as before. I know that lodash `merge` ignores `undefined` values but I don't thing it merges arrays the same way that our current `object-assign-deep` does. However it looks as though the `customizer` function in `mergeWith` allows finer control over that:

https://lodash.com/docs/4.16.6#mergeWith

**Comment by giuseppeg** [comment]
In this case we can roll our own fix I guess

```javascript
var flags = [
  'minify',
  'encapsulate',
  'root',
  'lint'
].reduce(function (acc, flag) {
  if (typeof flag !== 'undefined') {
    acc[flag] = program[flag]
  }
  return acc
}, {})

var opts = assign({}, config, flags)
```
