### ISSUE TITLE
stylelint

### ISSUE THREAD

**Issue by rocketspops** [suitcss/preprocessor#58]
Using version 3.0.0 of the suitcss preprocessor, stylelint is reporting warnings for the normalize.css in the node_modules directory:

``` bash
node_modules/normalize.css/normalize.css
12:3    ⚠  Unexpected vendor-prefix "-ms-text-size-adjust" (property-no-vendor-prefix) [stylelint]
13:3    ⚠  Unexpected vendor-prefix "-webkit-text-size-adjust" (property-no-vendor-prefix) [stylelint]
96:3    ⚠  Unexpected vendor-prefix "-webkit-text-decoration-skip" (property-no-vendor-prefix) [stylelint]
212:1   ⚠  Unexpected composition (selector-root-no-composition) [stylelint]
306:3   ⚠  Unexpected vendor-prefix "-webkit-appearance" (property-no-vendor-prefix) [stylelint]
392:3   ⚠  Unexpected vendor-prefix "-webkit-appearance" (property-no-vendor-prefix) [stylelint]
402:3   ⚠  Unexpected vendor-prefix "-webkit-appearance" (property-no-vendor-prefix) [stylelint]
409:3   ⚠  Unexpected vendor-prefix "::-webkit-input-placeholder" (selector-no-vendor-prefix) [stylelint]
420:3   ⚠  Unexpected vendor-prefix "-webkit-appearance" (property-no-vendor-prefix) [stylelint]
```

I was able to suppress these warnings by including a .stylelintignore file in my project. I was looking through the stylelint-config-suitcss docs, and it seems like the intent is for the node_modules directory to be ignored by default?

**Comment by simonsmith** [comment]
Hey @rocketspops,

What part of the docs mentions `node_modules`? Couldn't see it.

I think ignoring modules might be best solved on an individual basis, but there could be an argument to say we should bake that in seeing as its included in `base`.

Thoughts @giuseppeg?

Another way to suppress it is with options:

``` js
{
  stylelint: {
    extends: 'stylelint-config-suitcss',
    configOverrides: {
      'ignoreFiles': '**/normalize.css'
    },
  },
}
```

**Comment by giuseppeg** [comment]
hi @rocketspops, I've experienced this "issue" myself

> it seems like the intent is for the node_modules directory to be ignored by default

Can you point me to the stylelint docs where they say this?

The reason why we are not ignoring `node_modules` by default is that you may import other 3rd parties modules like `suitcss-components-grid` that should be linted imo.

**Comment by giuseppeg** [comment]
oops we composed a similar comment at the same time.
We could make an exception for `suitcss-base` maybe although hard coding single use cases is a bit a code smell.

**Comment by simonsmith** [comment]
Yeah, I'd vote for leaving it up to the user. I've had this problem with stylelint-config-suitcss and normalize for some time and it's only a minor annoyance to add an exception.

**Comment by giuseppeg** [comment]
> 3rd parties modules like suitcss-components-grid that should be linted imo

On a second thought maybe it is silly to lint 3rd parties modules because chances are that you can't quick fix linter errors that originates from other's people code.

Maybe we should ignore `node_modules` altogether.

**Comment by briandrum** [comment]
I think there is value in listing 3rd party modules, as it give you the opportunity to submit a PR, use your own fork, or choose a different module entirely.

**Comment by rocketspops** [comment]
@giuseppeg @simonsmith Looking closer, I made an incorrect assumption about the intent to ignore `node_modules` by default. In my haste, I conflated the need for `.stylelintignore` to leverage `.gitignore` pattern matching with `node_modules` being listing in the `.gitignore` file within the stylelint-config-suitcss repo. Rookie, I know.

In an event, @giuseppeg mirrored my thoughts exactly in that you can't easily/quickly fix linting errors/warning in other people's code. I agree with @briandrum (hey, man! I owe you an email) however--had it been a file other than normalize.css, it might have given me some pause. 

In this case, the `.stylelintignore` suffices. @simonsmith thanks for the configuration tip! I tried to set `ignoreFiles` without `configOverrides`.

**Comment by simonsmith** [comment]
Sounds like this is resolved?

**Comment by simonsmith** [comment]
It's a minor configuration change to ignore node_modules though.

**Comment by giuseppeg** [comment]
fyi it seems like that 

> The ignoreFiles property is stripped from extended configs: only the root-level config can ignore files.

So the only way to ignore files in suit is to add a `.stylelintignore` file at the root of the project like @rocketspops suggested.

I read that there is an option `ignorePath` but I have tried it.

**Comment by giuseppeg** [comment]
> Imho we should ignore node_modules

For instance ESLint doesn't lint dependencies

**Comment by briandrum** [comment]
I see. Thank you for investigating @giuseppeg.

**Comment by rocketspops** [comment]
Yes, I think so. Thanks!

**Comment by simonsmith** [comment]
FYI I was able to this config to suppress the warnings:

``` js
module.exports = {
  stylelint: {
    extends: 'stylelint-config-suitcss',
    ignoreFiles: '**/normalize.css',
    rules: {},
  },
};
```

**Comment by briandrum** [comment]
Ha, that works for me too. I don't know what I was doing differently before that it was choking on.

Thanks for sharing.

**Comment by simonsmith** [comment]
@briandrum Yeah, I realised Stylelint chokes without a `rules` object, so you have to include it regardless. I think I led you down the wrong path last time, heh.

**Comment by danalloway** [comment]
just to add some clarity for others finding this issue (coming from someone who is using all of this for the first time today)

the config @simonsmith is talking about is a `postcss.config.js` config file not a `stylelint.config.js`
you will need to create this file in the root of your project then use it by adding the `-c` parameter option when you run `suitcss`

hopet his helps

**Comment by simonsmith** [comment]
Whoops, yes good point 👍

**Comment by simonsmith** [comment]
> For instance ESLint doesn't lint dependencies

Based on that, perhaps we should make a change to ignore anything in `node_modules`? This issue seems to be causing hassle for users.

**Comment by giuseppeg** [comment]
So we've got 5 partecipants to this conversation. 

Let's vote:
👍 ignore `node_modules`
👎 keep the status-quo

**Comment by simonsmith** [comment]
Seems like we should ignore `node_modules` then. Perhaps one to add before the next release

**Comment by giuseppeg** [comment]
in theory this is a breaking change but I guess that nobody will notice or care

**Comment by simonsmith** [comment]
Or it could be a bug fix, depending on how we look at it

**Comment by rocketspops** [comment]
👍 for ignoring

**Comment by giuseppeg** [comment]
Does anyone have time to open an issue on stylelint and figure out if this is a bug and should be fixed there rather than in preprocessor? 
https://gitter.im/stylelint/stylelint?at=58309b1e2cf343a318c869e6

**Comment by simonsmith** [comment]
I had a look into it and opened [https://github.com/stylelint/stylelint/issues/2149](https://github.com/stylelint/stylelint/issues/2149).

**Comment by simonsmith** [comment]
https://github.com/stylelint/stylelint/pull/2171

**Comment by simonsmith** [comment]
Going to consider this closed now. We'll pick up the fix when stylelint next releases a patch
