### ISSUE TITLE
--import-root is being ignored

### ISSUE THREAD

**Issue by casio** [suitcss/preprocessor#64]
Give an entry file in `<project-root>/src/index.css`, running
`$<project-root>: suitcss --import-root ./src index.css dist.css` will throw:

`not found · <project-root>/index.css`

Seems, the option is just ignored?

**Comment by simonsmith** [comment]
Do you get the same problem `-i`?

**Comment by casio** [comment]
yup, same thing

fyi I'm on mac os
```
node v6.9.1
npm 3.10.8
suitcss 3.0.0
```

**Comment by simonsmith** [comment]
@giuseppeg I think it might be since we added this merging of options - https://github.com/suitcss/preprocessor/blob/master/bin/suitcss#L113-L123

It comes in from the `bin` as `importRoot` but the node API is expecting `root`. We might need to translate that option manually.

**Comment by giuseppeg** [comment]
> It comes in from the bin as importRoot but the node API is expecting root. We might need to translate that option manually.

Right.

FWIW the snippet you linked has not been released yet.

**Comment by simonsmith** [comment]
> FWIW the snippet you linked has not been released yet.

Oh yeah! Needs more than my cursory glance then

**Comment by simonsmith** [comment]
I'll investigate this later

**Comment by casio** [comment]
@simonsmith thx for the hint (and the prompt reaction)!
however, no luck even with a config file - `"root": "./src"` seems to be ignored, as well.

also, I found that using json as the config fmt, raises: `SyntaxError: Unexpected token : `.
using a js file does not raise, though.

want me to create a new issue for this one?

**Comment by simonsmith** [comment]
@casio Yes please. I'll investigate that too

**Comment by casio** [comment]
done. see #65

**Comment by casio** [comment]
so I started working on a fix for `importRoot` a little: https://github.com/casio/preprocessor/tree/fix/import-root

the `root` vs `importRoot` ambiguity should be handled as well, I guess? which one do you prefer?
also related: should output go there as well?

**Comment by simonsmith** [comment]
Sorry @casio I totally missed that you had already started working on a fix there! Do you fancy rebasing that branch and opening a PR? We can move discussion there :)

**Comment by giuseppeg** [comment]
see [#69](https://github.com/suitcss/preprocessor/pull/69#issuecomment-265475580)
