### ISSUE TITLE
Deprecation of root rules

### ISSUE THREAD

**Issue by simonsmith** [suitcss/preprocessor#73]
See the thread here - https://github.com/stylelint/stylelint/issues/2226

It seems likely that if we want to keep these rules we should come up with a stylelint plugin. Maybe a good time to discuss the validity of the three root rules:

* `custom-property-no-outside-root`
* `root-no-standard-properties`
* `selector-root-no-composition`

**Comment by giuseppeg** [comment]
Can't we add them to `stylelint-config-suitcss`?

**Comment by simonsmith** [comment]
They exist as actual rules in the Stylelint core - https://github.com/stylelint/stylelint/tree/master/lib/rules/custom-property-no-outside-root

Once they're removed we'll have to load them from somewhere. `stylelint-config-suitcss` is just a configuration for those rules so I think we'll need to create a plugin and publish it.

As per @jeddy3's comment:

> The community will then have time, and if there is the desire, to convert these rules to plugins before they are removed outright in 8.0.0. We took the same approach with 7.0.0 and it worked well.

**Comment by giuseppeg** [comment]
ah gotcha, I missed that part. Is it a lot of work to make a single plugin that includes them all?

**Comment by simonsmith** [comment]
I don't think so, just wanted to get your opinion before heading that direction

**Comment by simonsmith** [comment]
It might be good to do so anyway as there may be other Stylelint users that depend on those rules, but I think we're the main dependency.

**Comment by jeddy3** [comment]
> ah gotcha, I missed that part. Is it a lot of work to make a single plugin that includes them all?

I think you might want to _write them as single plugins_ (focused code that easy to test), but _publish them as a plugin pack_ (like [stylelint-scss](https://github.com/kristerkari/stylelint-scss) or [stylelint-order](https://github.com/hudochenkov/stylelint-order)). Publishing as a plugin pack is just as easy as publishing single plugins.

You can use a common [namespace](https://stylelint.io/developer-guide/plugins/#writing-plugins), e.g. `suitcss/` for each of the plugins.

For an example of converting a core rule to a plugin, you can take a looksie as [stylelint-no-browser-hacks](https://github.com/Slamdunk/stylelint-no-browser-hacks/blob/master/lib/index.js) — which is a convert of core [no-browser-hacks](https://github.com/stylelint/stylelint/blob/master/lib/rules/no-browser-hacks/index.js) rule.

Also, feel free to mention me if you've any questions :)

**Comment by simonsmith** [comment]
Ah, thanks for the tips.

**Comment by giuseppeg** [comment]
> I think you might want to write them as single plugins

yes sorry I was being lazy :)

**Comment by simonsmith** [comment]
Done in https://github.com/suitcss/stylelint-suitcss

Will open a PR on the Stylelint repo
