### ISSUE TITLE
Add postcss-initial to build chain.

### ISSUE THREAD

**Issue by Ross-Esmond** [suitcss/preprocessor#83]
postcss-autoreset uses `initial` which is not compatible with IE 11. postcss-autoreset actually recommends running css through postcss-initial as well to add support for IE 11. If suitcss wants to support IE 11 it should throw postcss-initial in the mix.

**Comment by giuseppeg** [comment]
We use `postcss-autoreset` only for an "experimental" feature which aims to isolate your components by resetting the inherited properties like `color` and non inherited ones like `float`. https://github.com/suitcss/preprocessor#encapsulate 

You can use additional plugins with SUIT CSS preprocessor meaning that you can also add `postcss-initial` if that's your thing.
